fix dependency issue between spring and jsonpath
'Spring boot currently depends on 0.9.1.
Upcoming Spring 4.1.2 required 1.1.0 as you will get a java.lang.NoClassDefFoundError:
com/jayway/jsonpath/Predicate otherwise.'

https://github.com/spring-projects/spring-boot/issues/1726